version: '3.8'
services:
  ollama-api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - app-network
    container_name: ollama-api
    pull_policy: always
    tty: true
    image: ollama/ollama:0.1.33-rc5

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    name: ollama-webui_ollama
    external: true
